### PR TITLE
Update

### PR DESCRIPTION
**Pull request by JayantGoel001**
1. Added Meta Tag
2. Added Media Query for Screen Size less than 592px.
3. Replaced var with let.
4. Added label for each input
5. Fixed Radio Button Issue.

### CODE REVIEW

**Review by CodingSpecies — APPROVED** [review]
It looks good to me. @AvidCoder101 see what you think.

**Comment by AvidCoder101** [comment]
@JayantGoel001 LGTM. Great work.

**Review by AvidCoder101 — APPROVED** [review]
LGTM

**Comment by AvidCoder101** [comment]
@all-contributors please add @JayantGoel001 for content

**Comment by JayantGoel001** [comment]
@AvidCoder101 @AvidCoder101 
Thank You

**Comment by JayantGoel001** [comment]
@AvidCoder101 @CodingSpecies 
Please invite me to this Organization.

**Comment by CodingSpecies** [comment]
@JayantGoel001 Invite is sent.

> @AvidCoder101 @CodingSpecies
> Please invite me to this Organization.

Invite Sent.

**Pull request merged**
