### PR TITLE
responsive site and styling

### PR DESCRIPTION
**Pull request by kmertzim**
Hello, i made the site responsive for mobile and fixed some styling issues.

### CODE REVIEW

**Comment by AvidCoder101** [comment]
Thanks for contributing @kmertzim!

**Comment by AvidCoder101** [comment]
@all-contributors please add @kmertzim for content

**Comment by CodingSpecies** [comment]
@kmertzim , thank you for contributing, it looks so much better now! I have sent an invite, for you to join our organisation. I am going to send how to accept and show others on your profile the organisation badge. Thank you so much again! 🥳

**Comment by CodingSpecies** [comment]
You have received an email to join, or press this link - https://github.com/CodingContributorsLair - , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
image

## 🎉🎊Welcome to the Organisation!!!🎉🎊

**Comment by kmertzim** [comment]
thanks everyone

**Pull request merged**
