### PR TITLE
Update index.css

### PR DESCRIPTION
**Pull request by thuongtruong1009**
small update

### CODE REVIEW

**Comment by AvidCoder101** [comment]
@thuongtruong1009 Thanks for contributing

**Review by AvidCoder101 — APPROVED** [review]
LGTM

**Comment by AvidCoder101** [comment]
@all-contributors please add @thuongtruong1009 for content

**Comment by CodingSpecies** [comment]
@thuongtruong1009 , I have sent you an invite to the organisation.

**Pull request merged**
