### PR TITLE
Button translate

### PR DESCRIPTION
**Pull request by sumitmukharjeeeeee**
Added clear button feature to clear the form and also animation for both buttons

### CODE REVIEW

**Review by AvidCoder101 — APPROVED** [review]
Thanks for contributing (:

**Comment by AvidCoder101** [comment]
@all-contributors please add @sumitmukharjeeeeee for content

**Comment by AvidCoder101** [comment]
I've sent you an invitation to the organization. Thanks (:

**Comment by sumitmukharjeeeeee** [comment]
thank you

**Pull request merged**
